"""User identity_url

Revision ID: 1ac1322c1639
Revises: 3ba1379c5b14
Create Date: 2013-09-05 14:43:53.162000

"""

# revision identifiers, used by Alembic.
revision = '1ac1322c1639'
down_revision = '3ba1379c5b14'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('identity_url', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'identity_url')
    ### end Alembic commands ###
