"""Modify user model: about_me and last_seen

Revision ID: 3ba1379c5b14
Revises: 58d953ca85cf
Create Date: 2013-09-04 11:26:54.659000

"""

# revision identifiers, used by Alembic.
revision = '3ba1379c5b14'
down_revision = '58d953ca85cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    ### end Alembic commands ###
