"""Create User table

Revision ID: 4588ff060fe1
Revises: None
Create Date: 2013-08-26 07:59:36.336000

"""

# revision identifiers, used by Alembic.
revision = '4588ff060fe1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True, unique=True),
    sa.Column('email', sa.String(length=120), nullable=True, unique=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
